#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define RES 70

#define OUTPUT 0
#define INPUT 1
#define LOW 0
#define HIGH 1


#define DELETE 0
#define MIRROR 1
#define NO_MIRROR 0
#define CLEAR 0
#define BLACK 1
#define WHITE 0
#define black 1
#define  white 0
#define LCDWIDTH 84
#define LCDHEIGHT 48
#define X_MAX 83
#define Y_MAX 47

#define CMD_DISPLAY_OFF   0xAE
#define CMD_DISPLAY_ON    0xAF


#define PCD8544_POWERDOWN 0x04
#define PCD8544_ENTRYMODE 0x02
#define PCD8544_EXTENDEDINSTRUCTION 0x01

#define PCD8544_DISPLAYBLANK 0x0
#define PCD8544_DISPLAYNORMAL 0x4
#define PCD8544_DISPLAYALLON 0x1
#define PCD8544_DISPLAYINVERTED 0x5

#define CMD_SET_DISP_NORMAL 0xC

#define MASK_Y_ADDRESS 0x40
#define MASK_X_ADDRESS 0x80

#define CMD_SET_DISP_REVERSE 0xD

#define CMD_SET_DISP_REVERSE 0xD

// H = 0
#define PCD8544_FUNCTIONSET 0x20
#define PCD8544_DISPLAYCONTROL 0x08
#define PCD8544_SETYADDR 0x40
#define PCD8544_SETXADDR 0x80

// H = 1
#define PCD8544_SETTEMP 0x04
#define PCD8544_SETBIAS 0x10
#define PCD8544_SETVOP 0x80
#define PCD8544_SPI_CLOCK_DIV SPI_CLOCK_DIV4

#define _rst  24
#define _cs   25
#define _dc   26
#define _din  27
#define _clk  28 
#define _bl   30

int pinMode(unsigned int pin, char Mode);
int digitalWrite(unsigned int pin, char Value);
int delayMicroseconds(unsigned int time);

char buffer_PCD8544[504] = {};
char clear[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
int bird_high[]={112,136,776,1292,1290,2194,2145,2049,2333,2723,1345,1345,1370,1348,1400,832,128};
char bird[] = { 112, 136, 8, 12, 10, 146, 97, 1, 29, 163, 65, 65, 90, 68, 120, 64, 128,
                  0,   0, 3,  5,  5,   8,  8, 8,  9,  10,  5,  5,  5,  5,   5,  3,   0}; 
                //  0,   0, 3,  5,  5,   8,  8, 8,  9,  10, 10, 10, 10, 10,  10, 10,  10}; 
//  0,   0, 3,  5,  5,   8,  8, 8,  9,  10,  5,  5,  5,  5,   5,  3,   0}; 

// this file generated by Image2GLCD
const unsigned char img[504] = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x80, 0x80, 0xC0, 0xC0, 0xC0, 0xE0, 0xE0, 0xE0, 0xE0, 0xE0, 0xE0, 0xC0, 0xE0, 0xA0, 0x10, 0x10, 
0x08, 0x04, 0x03, 0x01, 0x02, 0x0C, 0x10, 0x60, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0xC0, 0xC0, 0xC0, 0xE0, 0xE0, 0xF0, 0xF8, 0xFC, 
0xFC, 0xFE, 0xFF, 0xEF, 0x77, 0x3F, 0x3B, 0x3B, 0x3B, 0x3B, 0x1B, 0x1B, 0x1F, 0x11, 0x2F, 0xFF, 
0xFF, 0x9F, 0x1F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x82, 0x7C, 
0x00, 0x00, 0x00, 0x77, 0x7E, 0x3C, 0x1C, 0x3E, 0x77, 0x73, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF0, 0xFC, 0xFE, 
0xFE, 0xFF, 0xFF, 0xFF, 0xFF, 0x8F, 0x2F, 0x77, 0x77, 0xFF, 0x2F, 0x07, 0x27, 0x4F, 0x17, 0x47, 
0x87, 0x03, 0x03, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x03, 0x07, 0x0F, 0x3F, 0xFF, 0xFF, 
0xFF, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0x66, 0x66, 0x66, 0x66, 0x66, 0x7E, 0x7E, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x0F, 0x1F, 0x3F, 0x7F, 0x7F, 0x7F, 0xFF, 0xFF, 0xEF, 0xC7, 0xE7, 0xFF, 0x78, 0x40, 0x40, 
0x40, 0x60, 0x6B, 0x70, 0xCF, 0xC0, 0x80, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0xC0, 0xE0, 0xE0, 0xC0, 0x80, 
0x40, 0x20, 0x3F, 0x3F, 0x3F, 0x30, 0x40, 0x80, 0x00, 0x00, 0x00, 0x86, 0xC6, 0xE6, 0xB6, 0x9E, 
0x8E, 0x86, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x03, 0x07, 0x0F, 0x0F, 0x1E, 
0x1A, 0x1C, 0x34, 0x3C, 0x68, 0x78, 0xF8, 0xF0, 0xF0, 0xE0, 0xF0, 0x18, 0x0C, 0x0F, 0x07, 0x03, 
0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC0, 0x30, 0x0F, 0x00, 0x00, 0x00, 0x19, 
0x19, 0x19, 0x19, 0x19, 0xD9, 0xD9, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 
0x01, 0x1F, 0x20, 0x40, 0x20, 0x20, 0x20, 0x20, 0x40, 0x40, 0x40, 0x40, 0x1E, 0x01, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x06, 0x06, 0x06, 0x06, 0x06, 0x07, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 
};

////////////////////////////////////////////////////////
char i=0;char j = 0;

////////////////////////////////////////////////////////

void send_DATA(char DATA);
void send_COMMAND(char COMMAND);
void LCD_init();
void draw_pixel(char col, char row, char data);
void picture(char _xsize, char _xpos, char _ypos, char _ysize, char *pic);
void gotoXY_pixel(char x, char y);
void show_bird(char _xsize, char _ysize, char _xpos, char _ypos, char num, int *object);

int fd24,fd25,fd26,fd27,fd28,fd29,fd30;
int fo24,fo25,fo26,fo27,fo28,fo29,fo30;
void main(void)
{
        int i = 0;
        int j = 0;
         fd24 = open("/gpio/pin24/direction",O_RDWR);
         fd25 = open("/gpio/pin25/direction",O_RDWR);
         fd26 = open("/gpio/pin26/direction",O_RDWR);
         fd27 = open("/gpio/pin27/direction",O_RDWR);
         fd28 = open("/gpio/pin28/direction",O_RDWR);
         fd29 = open("/gpio/pin29/direction",O_RDWR);
         fd30 = open("/gpio/pin30/direction",O_RDWR);
        fo24 = open("/gpio/pin24/value",O_RDWR);
    fo25 = open("/gpio/pin25/value",O_RDWR);
    fo26 = open("/gpio/pin26/value",O_RDWR);
    fo27 = open("/gpio/pin27/value",O_RDWR);
    fo28 = open("/gpio/pin28/value",O_RDWR);
    fo29 = open("/gpio/pin29/value",O_RDWR);
    fo30 = open("/gpio/pin30/value",O_RDWR);

        LCD_init();
        digitalWrite(_bl,HIGH);
        

        gotoXY_pixel(0,0);
        for(i=0;i<504;i++){
                //if(i==17)gotoXY_pixel(20,1);
                send_DATA(img[i]);
                printf("i = %d, <%d>\n",i,img[i]);
                usleep(1000);
        }
        //digitalWrite(_bl,LOW);
        printf("modify v3.3\n");
        
  
}
void send_DATA(char DATA)
{
  char i = 0;
  digitalWrite(_cs,LOW);
  digitalWrite(_dc,HIGH);
  for(i=0;i<8;i++){
    if(DATA&(0x80))digitalWrite(_din,HIGH);
    else digitalWrite(_din,LOW);
    digitalWrite(_clk,HIGH);
    usleep(100);
    DATA = DATA << 1;
    digitalWrite(_clk,LOW);
    usleep(100);
  }
  digitalWrite(_cs,HIGH);

}
void send_COMMAND(char COMMAND)
{
  
  digitalWrite(_cs,LOW);
  digitalWrite(_dc,LOW);
  for(i = 0;i<8;i++){
    if((COMMAND&(0x80>>i)) == (0x80>>i))digitalWrite(_din,HIGH);
    else digitalWrite(_din,LOW);
  digitalWrite(_clk,HIGH);
    delayMicroseconds(1);
    digitalWrite(_clk,LOW);
    delayMicroseconds(1);
  }
  digitalWrite(_cs,HIGH);
}
void LCD_init() 
{
  pinMode(_rst, OUTPUT);
  pinMode(_cs, OUTPUT);
  pinMode(_din,OUTPUT);
  pinMode(_clk,OUTPUT);
  pinMode(_dc, OUTPUT);
  pinMode(_bl, OUTPUT);

  //digitalWrite(_rst,LOW);      
  digitalWrite(_bl,LOW);
  digitalWrite(_rst,HIGH);       
  digitalWrite(_cs,LOW);

  send_COMMAND(PCD8544_FUNCTIONSET|PCD8544_EXTENDEDINSTRUCTION);
  send_COMMAND(PCD8544_SETVOP|RES);
  send_COMMAND(PCD8544_FUNCTIONSET);
  send_COMMAND(PCD8544_DISPLAYCONTROL|PCD8544_DISPLAYNORMAL);

  digitalWrite(_cs,HIGH);
}

void gotoXY_pixel(char x, char y)
{
  /////////////////////SET Y-ADDRESS OF RAM/////////////////
  digitalWrite(_cs,LOW);
  digitalWrite(_dc,LOW);
  if(y<0)y=0;
  if(y>5)y=5;
  send_COMMAND(MASK_Y_ADDRESS|y);
  digitalWrite(_cs,HIGH);
  /////////////////////SET X-ADDRESS OF RAM/////////////////
  digitalWrite(_cs,LOW);
  digitalWrite(_dc,LOW);
  if(x<0)x=0;
  if(x>83)x=83;
  send_COMMAND(MASK_X_ADDRESS|x);
  digitalWrite(_cs,HIGH);
}



int pinMode(unsigned int pin, char Mode)
{
        switch(pin){
                case 24:
                        if(Mode == OUTPUT){
                                write(fd24,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd24,"in",3);
                        }
                        break;
                case 25:
                        if(Mode == OUTPUT){
                                write(fd25,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd25,"in",3);
                        }
                        
                        break;
                case 26:
                        if(Mode == OUTPUT){
                                write(fd26,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd26,"in",3);
                        }
                        
                        break;
                case 27:
                        if(Mode == OUTPUT){
                                write(fd27,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd27,"in",3);
                        }
                        
                        break;
                case 28:
                        if(Mode == OUTPUT){
                                write(fd28,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd28,"in",3);
                        }
                        
                        break;
                case 29:
                        if(Mode == OUTPUT){
                                write(fd29,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd29,"in",3);
                        }
                        
                        break;
                case 30:
                        if(Mode == OUTPUT){
                                write(fd30,"out",3);
                        }
                        else if(Mode == INPUT){
                        write(fd30,"in",3);
                        }
                        
                        break;
                
                default:
                        printf("UNKOWN pin\n");
                        return -1;
        }
        
        return 1;
}

int digitalWrite(unsigned int pin, char Value)
{
        switch(pin){
                
                case 24:
                        if(Value == LOW){
                                write(fo24,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo24,"1",2);
                        }
                       break;
                case 25:
                        if(Value == LOW){
                                write(fo25,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo25,"1",2);
                        }
                        break;
                case 26:
                        if(Value == LOW){
                                write(fo26,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo26,"1",2);
                        }
                        break;
                case 27:
                        if(Value == LOW){
                                write(fo27,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo27,"1",2);
                        }
                        break;
                case 28:
                        if(Value == LOW){
                                write(fo28,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo28,"1",2);
                        }
                        break;
                case 29:
                        if(Value == LOW){
                                write(fo29,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo29,"1",2);
                        }
                        break;
                case 30:
                        if(Value == LOW){
                                write(fo30,"0",2);
                        }
                        else if(Value == HIGH){
                                write(fo30,"1",2);
                        }
                        break;
                
                default:
                        printf("UNKOWN pin\n");
                        return -1;
                
        }
        return 1;
}
int delayMicroseconds(unsigned int time)
{
  usleep(time*1000);
}
